### ISSUE TITLE
Pytorch implementation

### ISSUE THREAD

**Issue by davidoort** [younggyoseo/MV-MWM#1]
Hi, thanks so much for making this open-source! Is there a pytorch implementation of this or anything in the works?

**Comment by younggyoseo** [comment]
Hi, we have a plan to re-implement our model in PyTorch but there's no concrete plan yet. We'll let you know when there's an update to this!

**Comment by zichunxx** [comment]
Hi! @younggyoseo The Pytorch version of MWM is also expected!
